version: 0.2
env:
  shell: /bin/bash
  variables:
    FLASK_IMAGE_REPO: 'sample/flask'
    FLASK_IMAGE_TAG: 1
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(/root/.pyenv/shims/aws ecr get-login --no-include-email --region ${AWS_DEFAULT_REGION})
  build:
    commands:
      - echo Build started on $(date)
      - echo Building the Docker image...
      - docker build -t ${FLASK_IMAGE_REPO}:${FLASK_IMAGE_TAG} .
      - docker tag ${FLASK_IMAGE_REPO}:${FLASK_IMAGE_TAG} ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${FLASK_IMAGE_REPO}:${FLASK_IMAGE_TAG}
  post_build:
    commands:
      - echo Build completed on $(date)
      - echo Pushing the Docker image...
      - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${FLASK_IMAGE_REPO}:${FLASK_IMAGE_TAG}
