version: "3"
services:
  webapp:
    image: flaskapp:0.1.0
    ports:
      - "80:8000/tcp"
    environment:
      - "memcachedURL=10.1.1.20"
    depends_on:
      - memcached
    networks:
      flask_net:
        ipv4_address: "10.1.1.10"

      
  memcached:
    image: memcached:1.6.6
    ports:
      - "11211:11211/tcp"
    networks:
      flask_net:
        ipv4_address: "10.1.1.20"

networks:
  flask_net:
    ipam:
      driver: default
      config:
        - subnet: "10.1.1.0/24"
