version: "3"
services:
  webapp:
    build:
      context: .
    image: flaskapp:0.1.3
    ports:
      - "80:8000/tcp"
    environment:
      - "memcachedURL=10.1.1.20"
      - "redisURL=10.1.1.30"
      - "redisPort=6379"
      - "memcachedPort=11211"
    depends_on:
      - memcached
      - redis
    networks:
      flask_net:
        ipv4_address: "10.1.1.10"

      
  memcached:
    image: memcached:1.6.6
    ports:
      - "11211:11211/tcp"
    networks:
      flask_net:
        ipv4_address: "10.1.1.20"
  
  redis:
    image: redis:6.0.6
    ports: 
      - "6379:6379/tcp"
    networks:
      flask_net:
        ipv4_address: "10.1.1.30"

networks:
  flask_net:
    ipam:
      driver: default
      config:
        - subnet: "10.1.1.0/24"
